### ISSUE TITLE
Функция get_only_audios() - offset всегда 30

### ISSUE THREAD

**Issue by ghost** [imartemy1524/vk_audio#6]
Функция get_only_audios(None, offset=100) всегда offset = 30. Ставь хоть 0,хоть 100,хоть вообще не писать его - всегда 30. Может быть я что-то не так делаю. Нужна помощь. Заранее спасибо.

**Comment by alan-novak** [comment]
Проблема в модуле `audio.py`, а конкретно в функции `load_audios`, которая вызывается из `get_only_audios`:
```python
if(offset is None):offset = len(self._audios);
if(owner_id is None):owner_id = self.owner_id;
else:offset = 30;
```
При вызове из `get_only_audios` `owner_id` не `None`, поэтому `offset` всегда будет 30. Не совсем понятно, зачем это сделано.

Решается удалением последней строки.

**Comment by GigXStudio** [comment]
Вопрос решён
