### ISSUE TITLE
Load() и get_by_id() всегда выдают False

### ISSUE THREAD

**Issue by qoymu** [imartemy1524/vk_audio#7]
Приветствую!
Несколько дней не могу разобраться, что делаю не так
Буду крайне благодарен, если укажите на ошибку
Заранее спасибо

Код:

```
import vk_api, vk_audio

vk_session = vk_api.VkApi(token='...')
vk = vk_audio.VkAudio(vk=vk_session)

owner = vk.uid
data = vk.load(owner)
print(data) # Выдает False

audios = "456239878"
audio_1 = vk.get_by_id(audios)
print(audio_1) # Аналогично, False 
```

**Comment by imartemy1524** [comment]
Здравствуйте!
Нужно авторизовываться через логин и пароль ( или через куку remixsid ), т.к. библиотека использует веб версию вк

**Comment by imartemy1524** [comment]
И еще, получать аудиозаписи надо методом load или get_only_audios

**Comment by qoymu** [comment]
Спасибо, буду пробовать

**Comment by qoymu** [comment]
Получилось зайти через куки, вариант с логином и паролем не мог использовать из-за двухфакторной аутентификации.
Спасибо Вам большое :)
